name: calculadora_imc
description: "Aplicativo Flutter para calcular o IMC."

# Impede a publicação acidental do pacote no pub.dev.
publish_to: 'none' 

# Versão do aplicativo.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependências do aplicativo.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/magreza_grau_1.png
    - assets/images/obesidade_grau_1.png
    - assets/images/obesidade_grau_2.png
    - assets/images/obesidade_grau_3.png
    - assets/images/eutrofia.png
    - assets/images/pre_obesidade.png
    - assets/images/default_image.png
